version: 2
updates:
  - package-ecosystem: "npm"          # change to your ecosystem
    directory: "/"                    # adjust path if needed
    schedule:
      interval: "weekly"             # daily, weekly, or monthly
    open-pull-requests-limit: 0      # disables version update PRs
