{
 "title": "Mainnet Sync",
 "time": { "from": "2025-03-04T15:46:00.000Z", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Base vs Latest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nec_base{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_base"
    },
    {
     "expr": "nec_execution_head{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_execution_head"
    }
   ]
  },
  {
   "title": "Buddies vs Block Import and Staged Header Lists",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "nec_sync_peers{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_sync_peers"
    },
    {
     "expr": "nec_sync_header_lists_staged{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_sync_header_lists_staged"
    },
    {
     "expr": "nec_sync_block_lists_staged{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_sync_block_lists_staged"
    }
   ]
  },
  {
   "title": "Unprocessed Headers and Blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "nec_sync_headers_unprocessed{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_sync_headers_unprocessed"
    },
    {
     "expr": "nec_sync_blocks_unprocessed{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_sync_blocks_unprocessed"
    }
   ]
  },
  {
   "title": "Additional RLPX Connections (non-Buddies)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "nec_sync_non_peers_connected{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nec_sync_non_peers_connected"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "process_virtual_memory_bytes"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "process_resident_memory_bytes"
    }
   ]
  },
  {
   "title": "Memory per GC instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=\"172.16.210.1:9099\", job=\"mainnet\"}",
     "legendFormat": "nim_gc_heap_instance_occupied_bytes"
    }
   ]
  }
 ]
}