{
 "title": "Nimbus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nimbus",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2s]) * 100",
     "legendFormat": "CPU usage %"
    },
    { "expr": "process_open_fds", "legendFormat": "open file descriptors" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" },
    { "expr": "nim_gc_mem_bytes", "legendFormat": "Nim GC mem total" },
    { "expr": "nim_gc_mem_occupied_bytes", "legendFormat": "Nim GC mem used" },
    { "expr": "connected_peers", "legendFormat": "connected peers" }
   ]
  },
  {
   "title": "peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expr": "connected_peers" }
   ]
  },
  {
   "title": "RSS mem",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[2s]) * 100"
    }
   ]
  }
 ]
}